"use client";

import { useEffect, useRef, useState } from "react";
import { normalizeRuntimeUrl } from "./lib/runtime-client";

type Workspace = { id: string; instance: string; deployment_id: string; restored_from: [string, string] | null };
type Snapshot = { id: string; label: string; created_at: number; sequence: number };
type Entry = { name: string; kind: "file" | "directory" | "symlink" | "special"; size: number | null };
type Preview = { kind: "text" | "image" | "binary" | "large"; text?: string; url?: string; size: number };
async function request<T>(base: string, path: string, body?: object, signal?: AbortSignal): Promise<T> {
  const response = await fetch(`${normalizeRuntimeUrl(base)}/v1/workspaces${path}`, {
    method: body ? "POST" : "GET", signal,
    ...(body ? { headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {}),
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
  return data;
}
function Content({ preview }: { preview: Preview }) {
  if (preview.kind === "text") return <pre className="artifact-text">{preview.text || "(Empty file)"}</pre>;
  // Only bounded raster data URLs generated by the runtime are displayed. HTML,
  // Markdown and SVG are shown as text; artifacts never run as same-origin UI.
  if (preview.kind === "image") return <img className="artifact-image" src={preview.url} alt="Artifact preview" />; // eslint-disable-line @next/next/no-img-element
  return <p>{preview.size.toLocaleString()} bytes · {preview.kind === "large" ? "Too large for the 512 KiB preview limit." : "Binary file."} Open the worktree in the editor to inspect it.</p>;
}

export function Artifacts({ serveUrl, onClose }: { serveUrl: string; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [selected, setSelected] = useState("");
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [version, setVersion] = useState("");
  const [directory, setDirectory] = useState("");
  const [entries, setEntries] = useState<Entry[]>([]);
  const [truncated, setTruncated] = useState(false);
  const [file, setFile] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [comparison, setComparison] = useState<Preview | null>(null);
  const [compare, setCompare] = useState(false);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [revision, setRevision] = useState(0);
  const [notice, setNotice] = useState("");
  const [editorUrl, setEditorUrl] = useState("");
  const alive = useRef(true);
  useEffect(() => {
    alive.current = true;
    const previous = document.activeElement as HTMLElement | null;
    dialog.current?.showModal();
    const current = dialog.current;
    return () => { alive.current = false; current?.close(); previous?.focus(); };
  }, []);
  useEffect(() => {
    const controller = new AbortController();
    void request<{workspaces: Workspace[]}>(serveUrl, "", undefined, controller.signal).then((data) => {
      setWorkspaces(data.workspaces);
      setSelected((current) => data.workspaces.some((w) => w.id === current) ? current : data.workspaces[0]?.id || "");
      setLoading(false);
    }).catch((e) => { if (!controller.signal.aborted) { setError(e.message); setLoading(false); } });
    return () => controller.abort();
  }, [serveUrl, revision]);
  useEffect(() => {
    if (!selected) return;
    const controller = new AbortController();
    void request<{snapshots: Snapshot[]}>(serveUrl, `/${selected}`, undefined, controller.signal).then((data) => setSnapshots(data.snapshots))
      .catch((e) => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [serveUrl, selected, revision]);
  useEffect(() => {
    if (!selected) return;
    const controller = new AbortController();
    void request<{entries: Entry[]; truncated: boolean}>(serveUrl, `/${selected}/browse`, { path: directory, snapshot: version || null }, controller.signal)
      .then((data) => { setEntries(data.entries); setTruncated(data.truncated); })
      .catch((e) => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [serveUrl, selected, version, directory, revision]);
  useEffect(() => {
    if (!selected || !file) return;
    const controller = new AbortController();
    void Promise.all([
      request<Preview>(serveUrl, `/${selected}/preview`, { path: file, snapshot: version || null }, controller.signal),
      compare && version ? request<Preview>(serveUrl, `/${selected}/preview`, { path: file }, controller.signal) : Promise.resolve(null),
    ]).then(([saved, current]) => { setPreview(saved); setComparison(current); })
      .catch((e) => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [serveUrl, selected, version, file, compare, revision]);
  function clearFile() { setFile(""); setPreview(null); setComparison(null); setError(""); }
  function selectWorkspace(id: string) {
    setSelected(id); setSnapshots([]); setVersion(""); setDirectory(""); setEntries([]); setEditorUrl(""); setNotice(""); clearFile();
  }
  async function openEditor() {
    // Open synchronously from the click to avoid popup blockers after startup.
    const tab = window.open("about:blank", "_blank");
    if (tab) tab.opener = null;
    setBusy(true); setError("");
    try {
      const data = await request<{url: string}>(serveUrl, `/${selected}/editor`, {});
      if (!alive.current) { tab?.close(); return; }
      setEditorUrl(data.url);
      if (tab) tab.location.replace(data.url);
      else setNotice("Editor ready. Use the editor link to open it.");
    } catch (e) { tab?.close(); if (alive.current) setError((e as Error).message); }
    finally { if (alive.current) setBusy(false); }
  }
  async function restore() {
    setBusy(true); setError("");
    try {
      const data = await request<{workspace: Workspace}>(serveUrl, `/${selected}/restore`, { snapshot: version });
      if (!alive.current) return;
      setWorkspaces((all) => [...all, data.workspace]); selectWorkspace(data.workspace.id);
      setNotice("Restored into a new workspace. The original files and running topology are unchanged."); setRevision((r) => r + 1);
    } catch (e) { if (alive.current) setError((e as Error).message); }
    finally { if (alive.current) setBusy(false); }
  }
  return <dialog ref={dialog} className="artifacts-dialog" aria-labelledby="artifacts-title" onCancel={onClose}>
    <header><div><span className="eyebrow">TEAM WORKSPACES</span><h2 id="artifacts-title">Files & versions</h2></div><button className="secondary-button" onClick={onClose} aria-label="Close files">Close</button></header>
    <div className="artifact-controls">
      <label>Team instance<select aria-label="Team workspace" disabled={busy} value={selected} onChange={(e) => selectWorkspace(e.target.value)}>
        {workspaces.map((w) => <option key={w.id} value={w.id}>{w.instance || "Root team"} · {w.id.slice(0, 8)}{w.restored_from ? " · restored" : ""}</option>)}
      </select></label>
      <label>Version<select aria-label="File version" disabled={!selected || busy} value={version} onChange={(e) => { setVersion(e.target.value); setDirectory(""); setEntries([]); clearFile(); }}>
        <option value="">Current worktree</option>
        {[...snapshots].reverse().map((s) => <option key={s.id} value={s.id}>#{s.sequence} {s.label} · {new Date(s.created_at * 1000).toLocaleString()}</option>)}
      </select></label>
      <button className="secondary-button" disabled={busy} onClick={() => { setError(""); setRevision((r) => r + 1); }}>Refresh</button>
      {version ? <button className="primary-button" disabled={busy} onClick={() => void restore()}>Restore as new workspace</button>
        : <button className="primary-button" disabled={!selected || busy} onClick={() => void openEditor()}>{busy ? "Starting editor…" : "Open in Web VS Code"}</button>}
    </div>
    <p className="artifact-guidance">{version ? "Saved version · read-only. Restore a copy to edit it." : "Edits save directly to this worktree. Agents may also be writing; stop the topology before making conflicting changes. Unsaved editor buffers are not included in snapshots."}</p>
    {editorUrl ? <p><a href={editorUrl} target="_blank" rel="noreferrer">Reopen editor ↗</a> · <button className="artifact-link" disabled={busy} onClick={() => { setBusy(true); void request(serveUrl, `/${selected}/editor/stop`, {}).then(() => { if (alive.current) { setEditorUrl(""); setNotice("Editor stopped. Topology state is unchanged."); } }).catch((e) => { if (alive.current) setError(e.message); }).finally(() => { if (alive.current) setBusy(false); }); }}>Stop editor</button></p> : null}
    {error ? <p className="connection-error" role="alert">{error}</p> : null}
    {notice ? <p role="status">{notice}</p> : null}
    {!selected ? <p>{loading ? "Loading workspaces…" : "No workspaces in this chat yet. Deploy a topology to create one."}</p> : <div className="artifact-body">
      <nav aria-label="Workspace files">
        <div className="artifact-path">worktree/{directory}</div>
        {directory ? <button onClick={() => { setDirectory(directory.split("/").slice(0, -1).join("/")); setEntries([]); clearFile(); }}>↰ Parent directory</button> : null}
        {entries.map((entry) => <button key={entry.name} disabled={entry.kind === "symlink" || entry.kind === "special"} title={entry.kind} onClick={() => {
          const path = directory ? `${directory}/${entry.name}` : entry.name;
          clearFile();
          if (entry.kind === "directory") { setDirectory(path); setEntries([]); } else setFile(path);
        }}><span>{entry.kind === "directory" ? "▸" : "·"}</span> {entry.name}{entry.kind === "symlink" ? " (link)" : ""}</button>)}
        {truncated ? <p>Showing the first 2,000 entries.</p> : null}
      </nav>
      <section aria-label="File preview" className="artifact-preview">
        {file ? <><div className="artifact-preview-title"><strong>{file}</strong>{version ? <label><input type="checkbox" checked={compare} onChange={(e) => { setCompare(e.target.checked); setComparison(null); setPreview(null); }} /> Compare with worktree</label> : null}</div>
          {preview ? <div className={comparison ? "artifact-comparison" : ""}><div>{comparison ? <h3>Saved version</h3> : null}<Content preview={preview} /></div>{comparison ? <div><h3>Current worktree</h3><Content preview={comparison} /></div> : null}</div> : <p>Loading preview…</p>}</>
          : <p>Select a file to preview it. Use Web VS Code to edit the current worktree.</p>}
      </section>
    </div>}
  </dialog>;
}
